### PR TITLE
Adding fix for decoding issue within http client

### PR DESCRIPTION
**Pull request by TonyRice**
Currently, doing something like retrieving google.com, will throw a decoding error. This effectively attempts to pull the charset from the headers and decode it properly

### CODE REVIEW

**Comment by wilzbach** [comment]
Umm having actual http requests to the outside world in the testsuite isn't great for a few reasons:
- local development with offline or slow internet
- random changes/outages from these sites now affect the testsuite
- testsuite can't be run in total isolation mode anymore

What's your opinion about mocking out `http fetch` with fixed replies?

**Comment by judepereira** [comment]
@wilzbach I hope the tests are in the integration directory. If they are, then it's okay. While we do have mocks in place, I like the idea of having real requests being made as part of the integration test suite.

**Comment by judepereira** [comment]
For local development, running unit tests should always be < 10 seconds.

**Comment by TonyRice** [comment]
Those are integration tests, I was going to use a story for those tests but just did that for a quick solution

**Pull request merged**
