### PR TITLE
Don't modify story during assignment

### PR DESCRIPTION
**Pull request by anukul**

### CODE REVIEW

**Comment by wilzbach** [comment]
Tests?

**Comment by anukul** [comment]
@seb updated, added test fails without this change.

**Comment by judepereira** [comment]
@anukul can you explain?

**Comment by anukul** [comment]
@judepereira [This](https://github.com/storyscript/runtime/blob/master/storyruntime/utils/Dict.py#L13) line modifies the story.

**Comment by judepereira** [comment]
@anukul Can't we just fix that instead of deep copying all the time?

**Comment by anukul** [comment]
@judepereira updated, thanks!

**Pull request merged**
