### PR TITLE
Upgrade Storyscript to 0.23.6

### PR DESCRIPTION
**Pull request by storyscript-infra**
Details: https://github.com/storyscript/storyscript/releases/tag/0.23.6

### CODE REVIEW

**Comment by judepereira** [comment]
@wilzbach looks like your bot is not basing the update on master @ HEAD

**Comment by judepereira** [comment]
(since CodeCov reports seem to be broken).

**Comment by wilzbach** [comment]
Na that's just Codecov being broken.

**Comment by TonyRice** [comment]
> Na that's just Codecov being broken.

I can confirm I've experienced this on a PR before. I tried deleting the comment by codecov, and re-running it.

**Pull request merged**
