### PR TITLE
Updating Lexicon execute to return enter line for streaming service

### PR DESCRIPTION
**Pull request by TonyRice**

### CODE REVIEW

**Comment by TonyRice** [comment]
This solves https://github.com/storyscript/runtime/issues/646

**Comment by judepereira** [comment]
@TonyRice - @williammartin, @anukul and I were on a call to discuss this, and decided to copy your changes to a newer branch, since Anukul ran `black` on the source which caused a merge conflict. We copied your changes to #652 

What we couldn't understand from your PR is why the test was updated for if_condition. Could you please explain that?

**Comment by TonyRice** [comment]
> @TonyRice - @williammartin, @anukul and I were on a call to discuss this, and decided to copy your changes to a newer branch, since Anukul ran `black` on the source which caused a merge conflict. We copied your changes to #652
> 
> What we couldn't understand from your PR is why the test was updated for if_condition. Could you please explain that?

Thank you guys! I did not mean to add that change in there. Originally I had a different fix, and forgot to remove the changes I made to the test. All is well

**Comment by TonyRice** [comment]
Closed with https://github.com/storyscript/runtime/pull/652

**Pull request closed without merging**
